'use strict';

module.exports = {
    up: async (queryInterface, Sequelize) => {
        return queryInterface.bulkInsert('Rooms', [
            {
                name: 'CT101',
                cinemaId: 1,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'CT102',
                cinemaId: 1,
                roomTypeId: 1,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'CT103',
                cinemaId: 1,
                roomTypeId: 1,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'CT201',
                cinemaId: 1,
                roomTypeId: 2,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'CT202',
                cinemaId: 1,
                roomTypeId: 2,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'CT301',
                cinemaId: 1,
                roomTypeId: 3,
                row: 8,
                col: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'CT302',
                cinemaId: 1,
                roomTypeId: 3,
                row: 8,
                col: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM101',
                cinemaId: 2,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM102',
                cinemaId: 2,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM103',
                cinemaId: 2,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM104',
                cinemaId: 2,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM105',
                cinemaId: 2,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM201',
                cinemaId: 2,
                roomTypeId: 2,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM202',
                cinemaId: 2,
                roomTypeId: 2,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM203',
                cinemaId: 2,
                roomTypeId: 2,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM301',
                cinemaId: 2,
                roomTypeId: 3,
                row: 8,
                col: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HCM302',
                cinemaId: 2,
                roomTypeId: 3,
                row: 8,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'VT101',
                cinemaId: 3,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'VT102',
                cinemaId: 3,
                roomTypeId: 1,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'VT103',
                cinemaId: 3,
                roomTypeId: 1,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'VT104',
                cinemaId: 3,
                roomTypeId: 1,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'VT201',
                cinemaId: 3,
                roomTypeId: 2,
                row: 8,
                col: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN101',
                cinemaId: 4,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN102',
                cinemaId: 4,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN103',
                cinemaId: 4,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN104',
                cinemaId: 4,
                roomTypeId: 1,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN201',
                cinemaId: 4,
                roomTypeId: 2,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN202',
                cinemaId: 4,
                roomTypeId: 2,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN203',
                cinemaId: 4,
                roomTypeId: 2,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN301',
                cinemaId: 4,
                roomTypeId: 3,
                row: 8,
                col: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'DN302',
                cinemaId: 4,
                roomTypeId: 3,
                row: 8,
                col: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'NT101',
                cinemaId: 5,
                roomTypeId: 1,
                row: 10,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'NT102',
                cinemaId: 5,
                roomTypeId: 1,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'NT103',
                cinemaId: 5,
                roomTypeId: 1,
                row: 10,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'NT201',
                cinemaId: 5,
                roomTypeId: 2,
                row: 8,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'NT202',
                cinemaId: 5,
                roomTypeId: 2,
                row: 8,
                col: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN101',
                cinemaId: 6,
                roomTypeId: 1,
                row: 16,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN102',
                cinemaId: 6,
                roomTypeId: 1,
                row: 16,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN103',
                cinemaId: 6,
                roomTypeId: 1,
                row: 16,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN104',
                cinemaId: 6,
                roomTypeId: 1,
                row: 16,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN201',
                cinemaId: 6,
                roomTypeId: 2,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN202',
                cinemaId: 6,
                roomTypeId: 2,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN203',
                cinemaId: 6,
                roomTypeId: 2,
                row: 12,
                col: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN301',
                cinemaId: 6,
                roomTypeId: 3,
                row: 8,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN302',
                cinemaId: 6,
                roomTypeId: 3,
                row: 8,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                name: 'HN303',
                cinemaId: 6,
                roomTypeId: 3,
                row: 8,
                col: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]);
    },

    down: async (queryInterface, Sequelize) => {
        return queryInterface.bulkDelete('Rooms', null, {});
    },
};
